### ISSUE TITLE
Typo in browser compatibility code

### ISSUE THREAD

**Issue by j-nava** [athanclark/purescript-float32#1]
I believe there's a typo in `Float32.js`: 

`var r = new Float32Array(1);
r[0] = s;
return r[0];`

should be

`var r = new Float32Array(1);
r[0] = x;
return r[0];`

**Comment by athanclark** [comment]
@j-nava Holy cow, you're absolutely right. Would you like to open a pull request?

**Comment by j-nava** [comment]
Sure, no problem. :)
